import type { Region, Business } from '@/types'

export const REGIONS: Region[] = [
  {
    id: 'vila_madalena',
    name: 'Vila Madalena',
    lat: -23.5505,
    lng: -46.6877,
    population_density: 12000,
    avg_income: 7500,
    age_distribution: { young: 0.45, adult: 0.40, senior: 0.15 },
    competition_density: 7.2,
    urban_flow: 8.5,
    consumption_trend: 9.0,
    description: 'Bairro boêmio com forte cultura artística e gastronômica.',
    highlights: ['Vida noturna intensa', 'Alta densidade de cafés', 'Público jovem'],
  },
  {
    id: 'moema',
    name: 'Moema',
    lat: -23.5997,
    lng: -46.6648,
    population_density: 14000,
    avg_income: 12000,
    age_distribution: { young: 0.25, adult: 0.55, senior: 0.20 },
    competition_density: 6.8,
    urban_flow: 7.8,
    consumption_trend: 8.5,
    description: 'Bairro nobre com foco em saúde e bem-estar.',
    highlights: ['Renda muito alta', 'Saúde e bem-estar', 'Adultos exigentes'],
  },
  {
    id: 'centro',
    name: 'Centro',
    lat: -23.5489,
    lng: -46.6388,
    population_density: 18000,
    avg_income: 2800,
    age_distribution: { young: 0.30, adult: 0.50, senior: 0.20 },
    competition_density: 9.5,
    urban_flow: 9.8,
    consumption_trend: 5.5,
    description: 'Centro histórico com altíssimo fluxo de pessoas.',
    highlights: ['Altíssimo fluxo diário', 'Renda baixa', 'Concorrência extrema'],
  },
  {
    id: 'pinheiros',
    name: 'Pinheiros',
    lat: -23.5660,
    lng: -46.6861,
    population_density: 11000,
    avg_income: 8500,
    age_distribution: { young: 0.40, adult: 0.45, senior: 0.15 },
    competition_density: 7.5,
    urban_flow: 8.8,
    consumption_trend: 9.2,
    description: 'Bairro vibrante com forte cena gastronômica e tecnológica.',
    highlights: ['Ecossistema de startups', 'Alta gastronomia', 'Jovens qualificados'],
  },
  {
    id: 'jardins',
    name: 'Jardins',
    lat: -23.5699,
    lng: -46.6520,
    population_density: 8000,
    avg_income: 18000,
    age_distribution: { young: 0.15, adult: 0.55, senior: 0.30 },
    competition_density: 5.5,
    urban_flow: 7.0,
    consumption_trend: 9.5,
    description: 'Bairro de luxo com maior renda per capita da cidade.',
    highlights: ['Renda altíssima', 'Consumo de luxo', 'Público sofisticado'],
  },
  {
    id: 'santo_andre',
    name: 'Santo André',
    lat: -23.6639,
    lng: -46.5383,
    population_density: 9500,
    avg_income: 4500,
    age_distribution: { young: 0.28, adult: 0.52, senior: 0.20 },
    competition_density: 5.8,
    urban_flow: 7.2,
    consumption_trend: 6.5,
    description: 'Cidade do ABC com forte base industrial e serviços.',
    highlights: ['Classe média', 'Base industrial forte', 'Menor custo'],
  },
  {
    id: 'campinas',
    name: 'Campinas',
    lat: -22.9099,
    lng: -47.0626,
    population_density: 7200,
    avg_income: 6200,
    age_distribution: { young: 0.35, adult: 0.45, senior: 0.20 },
    competition_density: 5.0,
    urban_flow: 7.5,
    consumption_trend: 7.8,
    description: 'Polo tecnológico e universitário com grande diversidade.',
    highlights: ['Polo tecnológico', 'Universidades', 'Crescimento acelerado'],
  },
  {
    id: 'itaquera',
    name: 'Itaquera',
    lat: -23.5400,
    lng: -46.4530,
    population_density: 16000,
    avg_income: 2200,
    age_distribution: { young: 0.42, adult: 0.45, senior: 0.13 },
    competition_density: 6.0,
    urban_flow: 7.8,
    consumption_trend: 5.0,
    description: 'Bairro periférico com alta densidade e público jovem.',
    highlights: ['Alta densidade', 'Público jovem', 'Renda baixa'],
  },
  {
    id: 'liberdade',
    name: 'Liberdade',
    lat: -23.5593,
    lng: -46.6336,
    population_density: 13000,
    avg_income: 4200,
    age_distribution: { young: 0.30, adult: 0.50, senior: 0.20 },
    competition_density: 7.0,
    urban_flow: 8.0,
    consumption_trend: 7.2,
    description: 'Bairro com forte identidade cultural asiática e turismo.',
    highlights: ['Identidade cultural única', 'Turismo constante', 'Gastronomia temática'],
  },
  {
    id: 'lapa',
    name: 'Lapa',
    lat: -23.5238,
    lng: -46.7018,
    population_density: 10500,
    avg_income: 5500,
    age_distribution: { young: 0.35, adult: 0.48, senior: 0.17 },
    competition_density: 6.2,
    urban_flow: 7.5,
    consumption_trend: 7.0,
    description: 'Bairro misto em crescimento com entretenimento forte.',
    highlights: ['Crescimento acelerado', 'Entretenimento noturno', 'Mix de renda'],
  },
  {
    id: 'santana',
    name: 'Santana',
    lat: -23.5028,
    lng: -46.6282,
    population_density: 13500,
    avg_income: 5800,
    age_distribution: { young: 0.20, adult: 0.50, senior: 0.30 },
    competition_density: 5.5,
    urban_flow: 7.0,
    consumption_trend: 6.8,
    description: 'Bairro familiar com forte presença de adultos e idosos.',
    highlights: ['Perfil familiar', 'Alta fidelização', 'Saúde e educação'],
  },
  {
    id: 'abc_paulista',
    name: 'ABC Paulista',
    lat: -23.6700,
    lng: -46.5600,
    population_density: 8800,
    avg_income: 4800,
    age_distribution: { young: 0.30, adult: 0.52, senior: 0.18 },
    competition_density: 5.2,
    urban_flow: 6.8,
    consumption_trend: 6.2,
    description: 'Região industrial com forte mercado de serviços técnicos.',
    highlights: ['Indústria forte', 'Serviços técnicos', 'Mercado estável'],
  },
]

export const BUSINESSES: Business[] = [
  {
    id: 'cafeteria',
    name: 'Cafeteria / Coffee Shop',
    icon: '🍵',
    sector: 'Alimentação',
    min_investment: 80000,
    ideal_income: 4000,
    ideal_age: 'mixed',
    competition_sensitivity: 0.7,
    description: 'Alta demanda em áreas com fluxo de jovens e trabalhadores.',
  },
  {
    id: 'restaurante_fitness',
    name: 'Restaurante Fitness',
    icon: '🥗',
    sector: 'Alimentação Saudável',
    min_investment: 120000,
    ideal_income: 6000,
    ideal_age: 'adult',
    competition_sensitivity: 0.6,
    description: 'Crescimento acelerado em bairros de alta renda com foco em saúde.',
  },
  {
    id: 'academia',
    name: 'Academia de Ginástica',
    icon: '💪',
    sector: 'Saúde e Bem-estar',
    min_investment: 200000,
    ideal_income: 5000,
    ideal_age: 'mixed',
    competition_sensitivity: 0.8,
    description: 'Alto investimento, mas mercado robusto em bairros emergentes.',
  },
  {
    id: 'coworking',
    name: 'Coworking Space',
    icon: '💻',
    sector: 'Serviços Corporativos',
    min_investment: 150000,
    ideal_income: 7000,
    ideal_age: 'young',
    competition_sensitivity: 0.5,
    description: 'Ideal em regiões com startups, freelancers e jovens profissionais.',
  },
  {
    id: 'brechó',
    name: 'Brechó / Moda Sustentável',
    icon: '♻️',
    sector: 'Moda e Varejo',
    min_investment: 30000,
    ideal_income: 3500,
    ideal_age: 'young',
    competition_sensitivity: 0.4,
    description: 'Tendência forte entre jovens conscientes. Baixo investimento.',
  },
  {
    id: 'pet_shop',
    name: 'Pet Shop / Veterinária',
    icon: '🐾',
    sector: 'Pet Care',
    min_investment: 90000,
    ideal_income: 5500,
    ideal_age: 'adult',
    competition_sensitivity: 0.6,
    description: 'Mercado em expansão em bairros de renda média-alta com famílias.',
  },
  {
    id: 'farmácia',
    name: 'Farmácia',
    icon: '💊',
    sector: 'Saúde',
    min_investment: 180000,
    ideal_income: 2500,
    ideal_age: 'mixed',
    competition_sensitivity: 0.9,
    description: 'Alta concorrência de redes, porém demanda constante.',
  },
  {
    id: 'escola_idiomas',
    name: 'Escola de Idiomas',
    icon: '📚',
    sector: 'Educação',
    min_investment: 70000,
    ideal_income: 4500,
    ideal_age: 'young',
    competition_sensitivity: 0.5,
    description: 'Alta demanda em bairros universitários e de profissionais qualificados.',
  },
  {
    id: 'bar_pub',
    name: 'Bar / Pub',
    icon: '🍺',
    sector: 'Entretenimento',
    min_investment: 100000,
    ideal_income: 3500,
    ideal_age: 'young',
    competition_sensitivity: 0.7,
    description: 'Melhor desempenho em bairros com vida noturna ativa.',
  },
  {
    id: 'loja_eletronicos',
    name: 'Loja de Eletrônicos',
    icon: '📱',
    sector: 'Varejo Tecnológico',
    min_investment: 120000,
    ideal_income: 4000,
    ideal_age: 'young',
    competition_sensitivity: 0.8,
    description: 'Concorrência forte de grandes redes, nichos especializados têm espaço.',
  },
  {
    id: 'salao_beleza',
    name: 'Salão de Beleza',
    icon: '💇',
    sector: 'Beleza e Estética',
    min_investment: 60000,
    ideal_income: 3000,
    ideal_age: 'mixed',
    competition_sensitivity: 0.6,
    description: 'Demanda constante em qualquer bairro, diferencial em regiões de alta renda.',
  },
  {
    id: 'delivery_comida',
    name: 'Delivery de Comida',
    icon: '🛵',
    sector: 'Alimentação',
    min_investment: 40000,
    ideal_income: 2500,
    ideal_age: 'mixed',
    competition_sensitivity: 0.75,
    description: 'Alto crescimento pós-pandemia. Baixo custo inicial com operação em nuvem.',
  },
]
